### Health Check
GET http://localhost:5050


#################################################
################ REGISTER #######################
#################################################

### Register valid user
POST http://localhost:5050/api/auth/register
Content-Type: application/json

{
  "email" : "test3@test.com",
  "username": "Test3",
  "password": "Password123"
}

#################################################
################ LOGIN ##########################
#################################################

### Login valid
POST http://localhost:5050/api/auth/login
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "Password123"
}


### ME test ###
GET http://localhost:5050/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtcDJ0cXF3dzAwMDBsZDRyang1dzUyYnciLCJpYXQiOjE3Nzg2MDIwNzgsImV4cCI6MTc3ODY4ODQ3OH0.xfBCymK3OJ2W80tbnOD5YYqF_pko2c832c5HLtXYgFk

###
POST http://localhost:5050/api/decks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtcDJ0cXF3dzAwMDBsZDRyang1dzUyYnciLCJpYXQiOjE3Nzg2MDIwNzgsImV4cCI6MTc3ODY4ODQ3OH0.xfBCymK3OJ2W80tbnOD5YYqF_pko2c832c5HLtXYgFk

{
  "title": "Math",
  "description": "Math deck"
}

###
POST http://localhost:5050/api/decks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtcDEzNjR3OTAwMDA3dml1ODgydW84M2kiLCJpYXQiOjE3Nzg1MDUyNDAsImV4cCI6MTc3ODU5MTY0MH0.SXJS4fViTM8ag_91YspexPmb7KgsaEVYL_ygQnoQ7ks

{
  "title": "Biology 2",
  "description": "Biology deck v2"
}


###
GET http://localhost:5050/api/decks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtcDEzNjR3OTAwMDA3dml1ODgydW84M2kiLCJpYXQiOjE3Nzg1MDUyNDAsImV4cCI6MTc3ODU5MTY0MH0.SXJS4fViTM8ag_91YspexPmb7KgsaEVYL_ygQnoQ7ks

#################################################
################ FLASHCARDS #####################
#################################################

### Create flashcard
POST http://localhost:5050/api/flashcards
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtcDEzNjR3OTAwMDA3dml1ODgydW84M2kiLCJpYXQiOjE3Nzg1MDUyNDAsImV4cCI6MTc3ODU5MTY0MH0.SXJS4fViTM8ag_91YspexPmb7KgsaEVYL_ygQnoQ7ks

{
  "question": "What is DNA?",
  "answer": "Genetic material",
  "deckId": "cmp18irns0003yvl77v7aiy0j"
}

###

### Create second flashcard
POST http://localhost:5050/api/flashcards
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtcDEzNjR3OTAwMDA3dml1ODgydW84M2kiLCJpYXQiOjE3Nzg1MDUyNDAsImV4cCI6MTc3ODU5MTY0MH0.SXJS4fViTM8ag_91YspexPmb7KgsaEVYL_ygQnoQ7ks

{
  "question": "What is RNA?",
  "answer": "Messenger molecule",
  "deckId": "cmp18irns0003yvl77v7aiy0j"
}

###

### Get flashcards for deck
GET http://localhost:5050/api/flashcards/cmp2tshe50002ld4r3gl0u1ld
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtcDJ0cXF3dzAwMDBsZDRyang1dzUyYnciLCJpYXQiOjE3Nzg2MDIwNzgsImV4cCI6MTc3ODY4ODQ3OH0.xfBCymK3OJ2W80tbnOD5YYqF_pko2c832c5HLtXYgFk

###
POST http://localhost:5050/api/ai/generate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtcDJ0cXF3dzAwMDBsZDRyang1dzUyYnciLCJpYXQiOjE3Nzg2MDIwNzgsImV4cCI6MTc3ODY4ODQ3OH0.xfBCymK3OJ2W80tbnOD5YYqF_pko2c832c5HLtXYgFk

{
  "prompt": "Basics of biology and DNA",
  "deckId": "cmp2tshe50002ld4r3gl0u1ld"
}